// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRH9ocbShwKTQmyYF3QkAk103CfKpHAX4',
    appId: '1:859477754755:android:8f8b4ae3d8b3bf59256cb6',
    messagingSenderId: '859477754755',
    projectId: 'recipeapp-f019b',
    storageBucket: 'recipeapp-f019b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeENrG2BFIuc8U7WxklVSwbCp5nSdOboc',
    appId: '1:859477754755:ios:9c183f09d0e1b491256cb6',
    messagingSenderId: '859477754755',
    projectId: 'recipeapp-f019b',
    storageBucket: 'recipeapp-f019b.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeENrG2BFIuc8U7WxklVSwbCp5nSdOboc',
    appId: '1:859477754755:ios:9c183f09d0e1b491256cb6',
    messagingSenderId: '859477754755',
    projectId: 'recipeapp-f019b',
    storageBucket: 'recipeapp-f019b.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );
}
